// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFp7sz2FZ3WEn_16bv0eYE4tUmyDPLhMI',
    appId: '1:44741937465:web:3b2df99d2d1e50a439c0e8',
    messagingSenderId: '44741937465',
    projectId: 'what-to-watch-1e75a',
    authDomain: 'what-to-watch-1e75a.firebaseapp.com',
    storageBucket: 'what-to-watch-1e75a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtqbPwr9dmzL6V-73WFKg7aQ1kHvZhfVM',
    appId: '1:44741937465:android:433390149da1724339c0e8',
    messagingSenderId: '44741937465',
    projectId: 'what-to-watch-1e75a',
    storageBucket: 'what-to-watch-1e75a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-NJ8dnGrRc44QZY4PEOu_PFdEq6vd7GI',
    appId: '1:44741937465:ios:7ac7eee1fb8d631e39c0e8',
    messagingSenderId: '44741937465',
    projectId: 'what-to-watch-1e75a',
    storageBucket: 'what-to-watch-1e75a.firebasestorage.app',
    iosBundleId: 'com.example.whatToWatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-NJ8dnGrRc44QZY4PEOu_PFdEq6vd7GI',
    appId: '1:44741937465:ios:7ac7eee1fb8d631e39c0e8',
    messagingSenderId: '44741937465',
    projectId: 'what-to-watch-1e75a',
    storageBucket: 'what-to-watch-1e75a.firebasestorage.app',
    iosBundleId: 'com.example.whatToWatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFp7sz2FZ3WEn_16bv0eYE4tUmyDPLhMI',
    appId: '1:44741937465:web:b61cb2d2c4defbc139c0e8',
    messagingSenderId: '44741937465',
    projectId: 'what-to-watch-1e75a',
    authDomain: 'what-to-watch-1e75a.firebaseapp.com',
    storageBucket: 'what-to-watch-1e75a.firebasestorage.app',
  );

}