// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb9SqwSfxY8n3qpgG4rimUSx6ebK1kt0s',
    appId: '1:731971805603:web:65b85bb55d5eb72f3bfa16',
    messagingSenderId: '731971805603',
    projectId: 'whattowatch-22ec4',
    authDomain: 'whattowatch-22ec4.firebaseapp.com',
    storageBucket: 'whattowatch-22ec4.firebasestorage.app',
    measurementId: 'G-QJZXPV2Q93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8Sfdj6dQA9ql_rhBxp4-0r1o7xmqhE_o',
    appId: '1:731971805603:android:efe7e2f98a5b93043bfa16',
    messagingSenderId: '731971805603',
    projectId: 'whattowatch-22ec4',
    storageBucket: 'whattowatch-22ec4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz7zpfkEsu5Jcc6f94D1J4yE1P-dse9KY',
    appId: '1:731971805603:ios:efa2d27df821f5b63bfa16',
    messagingSenderId: '731971805603',
    projectId: 'whattowatch-22ec4',
    storageBucket: 'whattowatch-22ec4.firebasestorage.app',
    iosBundleId: 'com.example.whatToWatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz7zpfkEsu5Jcc6f94D1J4yE1P-dse9KY',
    appId: '1:731971805603:ios:efa2d27df821f5b63bfa16',
    messagingSenderId: '731971805603',
    projectId: 'whattowatch-22ec4',
    storageBucket: 'whattowatch-22ec4.firebasestorage.app',
    iosBundleId: 'com.example.whatToWatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb9SqwSfxY8n3qpgG4rimUSx6ebK1kt0s',
    appId: '1:731971805603:web:dafddf536975e82b3bfa16',
    messagingSenderId: '731971805603',
    projectId: 'whattowatch-22ec4',
    authDomain: 'whattowatch-22ec4.firebaseapp.com',
    storageBucket: 'whattowatch-22ec4.firebasestorage.app',
    measurementId: 'G-VED4WBPSNH',
  );
}
